name: break_the_chain
description: A new Flutter application for social distancing monitoring for this pandemic period and for knowing stats of covid-19 cases in India.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1
environment:
  sdk: ">=2.7.0 <3.0.0"
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.3
  http: ^0.12.2
  flutter_spinkit: ^4.1.2
  quartet: ^0.1.1
  geolocator: ^6.0.0
dev_dependencies:
  flutter_test:
    sdk: flutter
flutter:
  uses-material-design: true
  assets:
    - images/
  fonts:
    - family: Satisfy
      fonts:
        - asset: fonts/Satisfy-Regular.ttf